source "https://rubygems.org"


gem "sinatra"
gem "sinatra-contrib"
gem "pry"
gem "rack-mini-profiler"
gem "mysql2"
gem "mysql2-cs-bind"
gem "erubis"
gem "unicorn"

# IDEA:
# gem 'newrelic'
# gem 'oj'
